<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZQvI41S\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZQvI41S/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerZQvI41S.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerZQvI41S\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerZQvI41S\appAppKernelProdContainer([
    'container.build_hash' => 'ZQvI41S',
    'container.build_id' => '4f3df4e2',
    'container.build_time' => 1709716784,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZQvI41S');
